bespokedbikes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from . import views
from django.urls import path

app_name = "core"

urlpatterns = [
    path('', views.index, name='index'),
    # salesperson
    path('salesperson/', views.salesperson_view, name='salesperson'),
    path('salesperson/update/<str:id>', views.salesperson_update, name="salesperson_update"),
    # product
    path('product/', views.product_view, name='product'),
    path('product/update/<str:id>', views.product_update, name="product_update"),
    # customer
    path('customer/', views.customer_view, name='customer'),
    # sales
    path('sale/', views.sale_view, name='sale'),
    # sales create
    path('sale/new', views.create_sale, name="new_sale"),
    # quarterly report
    path('sale_report/', views.sale_report, name="sale_report"),
    
    
    #
    # REST API
    path('api/product-details/', views.product_details, name="product_details"),
    path('api/saler-details/', views.saler_details, name="saler_details"),
    path('api/customer-details/', views.customer_details, name="customer_details"),

    
    # samples
    path('seed_sample/', views.seed_sample, name="seed_sample"),
    path('small_sample/', views.small_sample, name="small_sample"),

]

core/models.py
from django.db import models
from django.forms import ValidationError

class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.TextField()
    phone = models.CharField(max_length=20, unique=True, blank=False)
    start_date = models.DateField()
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class Salesperson(models.Model):
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    address = models.TextField(blank=False)
    phone = models.CharField(max_length=20, blank=False, unique=True)
    start_date = models.DateField()
    termination_date = models.DateField(null=True, blank=True)
    manager = models.CharField(max_length=100, blank=False)
    
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"
    
    def clean(self):
        super().clean()

        if self.start_date and self.termination_date and self.start_date > self.termination_date:
            raise ValidationError("Termination date must be later than the start date.")
    

class Product(models.Model):
    name = models.CharField(max_length=100, blank=False)
    manufacturer = models.CharField(max_length=100, blank=False)
    style = models.CharField(max_length=50, blank=False, default="Other")
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    sale_price = models.DecimalField(max_digits=10, decimal_places=2)
    qty_on_hand = models.PositiveIntegerField()
    commission_percentage = models.DecimalField(max_digits=5, decimal_places=2)
    
    class Meta:
        unique_together = ('name', 'manufacturer')

    def __str__(self):
        return f"{self.name} by {self.manufacturer} ${self.sale_price}"

class Sale(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    salesperson = models.ForeignKey(Salesperson, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    sales_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    salesperson_commission = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"{self.product.name} {self.sales_date} ${self.price} - Orig: ${self.product.sale_price} {'DISCOUNTED' if self.price == self.product.sale_price else ''}"

class Discount(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    begin_date = models.DateField()
    end_date = models.DateField()
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2)
    
    def __str__(self):
        return f"{self.product.name} by {self.product.manufacturer} - {self.discount_percentage}"

core/forms.py
from django import forms
from .models import *

class SalespersonForm(forms.ModelForm):
    class Meta:
        model = Salesperson
        fields = '__all__'

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = '__all__'

core/views.py
import json
from django.db import IntegrityError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from .forms import *
from django.views.decorators.csrf import csrf_exempt
from django.db.models.functions import ExtractYear
from django.core.paginator import Paginator
from .query import *
from django.db.models import Min, Max
from .utils import *

def index(request):
    return render(request, "core/apps.html", {
        "apps_link": get_apps_link()
    })

def salesperson_view(request):
    data = Salesperson.objects.all()
    paginator = Paginator(data, 50)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, "core/salesperson.html", {
        "data": page,
        "apps_link": get_apps_link()
    })


def salesperson_update(request, id):
    salesperson_data = Salesperson.objects.get(id=id)
    if request.method == 'POST':
        form = SalespersonForm(request.POST, instance=salesperson_data)
        if form.is_valid():
            form.save()
            return redirect(reverse("core:salesperson"))
    else:
        form = SalespersonForm(instance=salesperson_data)

    return render(request, "core/salesperson_update.html", {
        "form": form,
        "data": salesperson_data,
        "apps_link": get_apps_link()
    })


def product_view(request):
    data = Product.objects.all()
    
    paginator = Paginator(data, 50)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    
    return render(request, "core/product.html", {
        "data": page,
        "apps_link": get_apps_link()
    })


def product_update(request, id):
    product_data = Product.objects.get(id=id)

    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product_data)
        if form.is_valid():
            try:
                form.save()
                return redirect(reverse("core:product"))
            except IntegrityError:
                form.add_error(
                    None, "Product with this name and manufacturer already exists.")
    else:
        form = ProductForm(instance=product_data)

    return render(request, "core/product_update.html", {
        "form": form,
        "data": product_data,
        "apps_link": get_apps_link()
    })


def customer_view(request):
    data = Customer.objects.all()
    paginator = Paginator(data, 50)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, "core/customer.html", {
        "data": page,
        "apps_link": get_apps_link()
    })


def sale_view(request):
    data = execute_custom_query(query_all_sales)
        
    oldest_date = format_date(Sale.objects.aggregate(
        oldest_date=Min('sales_date'))['oldest_date'])
    nearest_date = format_date(Sale.objects.aggregate(
        nearest_date=Max('sales_date'))['nearest_date'])
    
    start_date = oldest_date
    end_date = nearest_date

    if request.method == 'POST':
        
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        data = execute_custom_query(query_sale_by_date_range, 
                                    [start_date, end_date])

    paginator = Paginator(data, 50)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    
    return render(request, "core/sale.html", {
        "apps_link": get_apps_link(),
        "data": page,
        "start_date": start_date,
        "end_date": end_date,
        "oldest_date": oldest_date,
        "nearest_date": nearest_date
    })


def create_sale(request):
    products = Product.objects.filter(qty_on_hand__gt=0)
    salespersons = []
    customers = []

    if request.method == 'POST':
        
        product = Product.objects.get(id=request.POST.get('product'))
        salesperson = Salesperson.objects.get(id=request.POST.get('salesperson'))
        customer = Customer.objects.get(id=request.POST.get('customer'))
        sales_date = format_date(request.POST.get('sales_date'))
       
        discounts = Discount.objects.filter(
            product=product,
            begin_date__lte=sales_date,
            end_date__gte=sales_date,
        )
        max_discount = discounts.order_by('-discount_percentage').first()

        if discounts:
            product_price = sale_calculate(product.sale_price,
                                           max_discount.discount_percentage,
                                           product.commission_percentage)
        else:
            product_price = sale_calculate(product.sale_price,
                                           0,
                                           product.commission_percentage)

        new_sale = Sale(product=product,
                        salesperson=salesperson,
                        customer=customer,
                        sales_date=sales_date,
                        price=product_price["sale_price"],
                        salesperson_commission=product_price["commission"])
        
        new_sale.save()
        
        qty = int(product.qty_on_hand)
        product.qty_on_hand = qty - 1
        product.save()
            
        return redirect(reverse("core:sale"))

    return render(request, "core/sale_create.html", {
        "apps_link": get_apps_link(),
        "products": products,
        "salesperson": salespersons,
        "customers": customers,
    })


def sale_report(request):
    stats = []
    
    report_title = ""

    year_range_query = Sale.objects.aggregate(min_year=Min(ExtractYear('sales_date')),
                                              max_year=Max(ExtractYear('sales_date')))

    min_year = year_range_query['min_year']
    max_year = year_range_query['max_year']

    if request.method == 'POST':
        year = int(request.POST.get('year'))
        quarter = int(request.POST.get('quarter'))
        
        report_title = f"{year} Report Q{quarter}"
        
        stats = execute_custom_query(query_sale_report_quarterly, [year, quarter])

    paginator = Paginator(stats, 50)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    
    return render(request, "core/sale_report.html", {
        "apps_link": get_apps_link(),
        "year_range": range(min_year, max_year + 1),
        "stats": page,
        "report_title": report_title
    })

def seed_sample(request):
    clean_data()
    add_sample_data()
    return HttpResponse("Feed data successfully.")

def small_sample(request):
    clean_data()
    add_small_data()
    return HttpResponse("Feed data successfully.")

@csrf_exempt
def saler_details(request):
    if request.method == 'POST':
        raw_data = request.body
        data_str = raw_data.decode('utf-8')
        data = json.loads(data_str)
        sales_date = data['sale_date']
        data = execute_custom_query(query_saler_by_sale_date, 
                                    [sales_date, sales_date])
        return JsonResponse(data, status=200, safe=False)
    else:
        return JsonResponse({'error': 'Unsupported HTTP method'}, status=405)

@csrf_exempt
def customer_details(request):
    if request.method == 'POST':
        raw_data = request.body
        data_str = raw_data.decode('utf-8')
        data = json.loads(data_str)
        sales_date = data['sale_date']
        print(sales_date)
        data = execute_custom_query(query_customer_by_sale_date, 
                                    [sales_date])

        return JsonResponse(data, status=200, safe=False)
    else:
        return JsonResponse({'error': 'Unsupported HTTP method'}, status=405)
  
@csrf_exempt
def product_details(request):
    if request.method == 'POST':
        raw_data = request.body
        data_str = raw_data.decode('utf-8')
        data = json.loads(data_str)
        sales_date = data['sale_date']
        
        product = Product.objects.get(id=data['id'])

        discounts = Discount.objects.filter(
            product=product,
            begin_date__lte=sales_date,
            end_date__gte=sales_date,
        )
        max_discount = discounts.order_by('-discount_percentage').first()

        if discounts:
            product_price = sale_calculate(product.sale_price,
                                           max_discount.discount_percentage,
                                           product.commission_percentage)
        else:
            product_price = sale_calculate(product.sale_price,
                                           0,
                                           product.commission_percentage)

        return JsonResponse(product_price, status=200, safe=False)
    else:
        return JsonResponse({'error': 'Unsupported HTTP method'}, status=405)

core/templates/core/apps.html
{% extends "core/base.html" %} {% block content %}
<div class="row row-cols-1 row-cols-md-4 g-4">

    {% for app in apps_link %}

    <div class="col ">
        <a href="{% url app.app_link %}" class="card text-bg-dark image-container shadow border-0 ">
            <div class="card-img-overlay">
                <h3 class="card-title">{{ app.app_name }}</h3>
                <p class="card-text">{{ app.app_info }}</p>
            </div>
        </a>
    </div>

    {% endfor %}

</div>
{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link rel="icon" href="{% static 'core/img/favicon.ico' %}" type="image/x-icon">
  <title>BeSpoked Bike</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
</head>

<body>

  {% include "core/nav.html" %}

  <div class="container-md ">

    <div class="card my-4 shadow border-0">
      <div class="card-body px-4 py-4">

    {% block content %}
    {% endblock %}

    </div>
    </div>


  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'core/js/scripts.js' %}"></script>
</body>

</html>

core/templates/core/customer.html
{% extends "core/base.html" %} {% block content %}

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Address</th>
      <th scope="col">Phone</th>
      <th scope="col">Start date</th>
    </tr>
  </thead>
  <tbody>
    {% for item in data %}

    <tr>
      <td>{{ item.first_name }}</td>
      <td>{{ item.last_name }}</td>
      <td>{{ item.address }}</td>
      <td>{{ item.phone }}</td>
      <td>{{ item.start_date }}</td>
    </tr>

    {% endfor %}
  </tbody>
</table>

<nav>
  <ul class="pagination justify-content-center">
    {% if data.has_previous %}
    <li class="page-item">
      <a href="?page={{ data.previous_page_number }}" class="page-link">Previous</a>
    </li>
    {% endif %}

    {% for i in data.paginator.page_range %}
      {% if data.number == i %}
      <li class="page-item active"><a class="page-link" href="">{{ i }}</a></li>

      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if data.has_next %}
      <a class="page-link" href="?page={{ data.next_page_number }}">Next</a>
    {% endif %}
  </ul>
</nav>

{% endblock %}

core/templates/core/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:index' %}">
      <img src="{% static 'core/img/favicon.jpg' %}" alt="" height="24" class="d-inline-block align-text-top">
      BeSpoked Bike
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        {% for app in apps_link %}
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name|lower == app.app_name|lower %}active{% endif %}"
            href="{% url app.app_link %}">{{ app.app_name }}</a>
        </li>
        {% endfor %}


      </ul>
    </div>
  </div>
</nav>

core/templates/core/product.html
{% extends "core/base.html" %} {% block content %}

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Manufacturer</th>
      <th scope="col">Style</th>
      <th scope="col">Purchase price ($)</th>
      <th scope="col">Sale price ($)</th>
      <th scope="col">Qty</th>
      <th scope="col">Commission (%)</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>

    {% for item in data %}

    <tr>
      <td>{{ item.name }}</td>
      <td>{{ item.manufacturer }}</td>
      <td>{{ item.style }}</td>
      <td>{{ item.purchase_price }}</td>
      <td>{{ item.sale_price }}</td>
      <td>{{ item.qty_on_hand }}</td>
      <td>{{ item.commission_percentage }}</td>
      <td>
        <a href="{% url 'core:product_update' item.id %}" class="btn btn-outline-primary btn-sm">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square"
            viewBox="0 0 16 16">
            <path
              d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
            <path fill-rule="evenodd"
              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
          </svg>
        </a>
      </td>
    </tr>

    {% endfor %}

  </tbody>
</table>

<nav>
  <ul class="pagination justify-content-center">
    {% if data.has_previous %}
    <li class="page-item">
      <a href="?page={{ data.previous_page_number }}" class="page-link">Previous</a>
    </li>
    {% endif %}

    {% for i in data.paginator.page_range %}
      {% if data.number == i %}
      <li class="page-item active"><a class="page-link" href="">{{ i }}</a></li>

      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if data.has_next %}
      <a class="page-link" href="?page={{ data.next_page_number }}">Next</a>
    {% endif %}
  </ul>
</nav>

{% endblock %}

core/templates/core/product_update.html
{% extends "core/base.html" %} {% block content %}
{% if form.non_field_errors %}
<span id="error-alert" class="text-danger">
  {% for error in form.non_field_errors %}
  <span>{{ error }}</span>
  {% endfor %}
</span>
{% endif %}

<div class="col-5">

<form method="post" class="row g-3">
  {% csrf_token %}

  <div class="col-12">
    <label class="form-label">Name</label>
    <input type="text" class="form-control" name="name" value="{{data.name}}">
    {% if form.errors.name %}
    <span id="error-alert" class="text-danger">{{ form.errors.name.0 }}</span>
    {% endif %}
  </div>
  <div class="col-12">
    <label class="form-label">Manufacturer</label>
    <input type="text" class="form-control" name="manufacturer" value="{{data.manufacturer}}">
    {% if form.errors.manufacturer %}
    <span id="error-alert" class="text-danger">{{ form.errors.manufacturer.0 }}</span>
    {% endif %}
  </div>
  <div class="col-12">
    <label class="form-label">Style</label>
    <input type="text" class="form-control" name="style" placeholder="1234 Main St" value="{{data.style}}">
    {% if form.errors.style %}
    <span id="error-alert" class="text-danger">{{ form.errors.style.0 }}</span>
    {% endif %}
  </div>
  <div class="col-12">
    <label class="form-label">Purchase price</label>
    <input type="text" class="form-control" name="purchase_price" placeholder="" value="{{data.purchase_price}}">
    {% if form.errors.purchase_price %}
    <span id="error-alert" class="text-danger">{{ form.errors.purchase_price.0 }}</span>
    {% endif %}
  </div>
  <div class="col-12">
    <label class="form-label">Sale price</label>
    <input type="text" class="form-control" name="sale_price" placeholder="" value="{{data.sale_price}}">
    {% if form.errors.sale_price %}
    <span id="error-alert" class="text-danger">{{ form.errors.sale_price.0 }}</span>
    {% endif %}
  </div>
  <div class="col-12">
    <label class="form-label">Qty on hand</label>
    <input type="text" class="form-control" name="qty_on_hand" placeholder="" value="{{data.qty_on_hand}}">
    {% if form.errors.qty_on_hand %}
    <span id="error-alert" class="text-danger">{{ form.errors.qty_on_hand.0 }}</span>
    {% endif %}
  </div>
  <div class="col-12">
    <label class="form-label">Commission percentage</label>
    <input type="text" class="form-control" name="commission_percentage" placeholder=""
      value="{{data.commission_percentage}}">
    {% if form.errors.commission_percentage %}
    <span id="error-alert" class="text-danger">{{ form.errors.commission_percentage.0 }}</span>
    {% endif %}
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Update</button>
  </div>
</form>

</div>

{% endblock %}

core/templates/core/sale.html
{% extends 'core/base.html' %} {% block content %}

<h2></h2>

<form class="row g-3 justify-content-center" method="POST">
  {% csrf_token %}
  <div class="col-sm-2">
    <input name="start_date" class="form-control" type="date" {% if start_date %} value={{ start_date }}
      {% elif oldest_date %} value={{ oldest_date }} {% endif %} {% if oldest_date %} min={{ oldest_date }} {% endif %}
      {% if nearest_date %} max={{ nearest_date }} {% endif %} />

    <label class="form-label text-muted">Start Date</label>
  </div>
  <div class="col-sm-2">

    <input name="end_date" class="form-control" type="date" {% if end_date %} value={{ end_date }}
      {% elif nearest_date %} value={{ nearest_date }} {% endif %} {% if oldest_date %} min={{ oldest_date }}
      {% endif %} {% if nearest_date %} max={{ nearest_date }} {% endif %} />

    <label class="form-label text-muted">End Date</label>
  </div>
  <div class="col-sm-2">
    <button type="submit" class="btn btn-primary">Apply</button>
  </div>
</form>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Sales Person</th>
      <th scope="col">Salesperson #</th>
      <th scope="col">Customer</th>
      <th scope="col">Customer #</th>
      <th scope="col">Sales Date</th>
      <th scope="col">Price ($)</th>
      <th scope="col">Commission (%)</th>
    </tr>
  </thead>
  <tbody>
    {% for item in data %}
    <tr>
      <td>{{ item.0 }}</td>
      <td>{{ item.2 }}, {{ item.1 }}</td>
      <td>{{ item.3 }}</td>
      <td>{{ item.5 }}, {{ item.4 }}</td>
      <td>{{ item.6 }}</td>
      <td>{{ item.7 }}</td>
      <td>{{ item.8 }}</td>
      <td>{{ item.9 }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<nav>
  <ul class="pagination justify-content-center">
    {% if data.has_previous %}
    <li class="page-item">
      <a href="?page={{ data.previous_page_number }}" class="page-link">Previous</a>
    </li>
    {% endif %}

    {% for i in data.paginator.page_range %}
      {% if data.number == i %}
      <li class="page-item active"><a class="page-link" href="">{{ i }}</a></li>

      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if data.has_next %}
      <a class="page-link" href="?page={{ data.next_page_number }}">Next</a>
    {% endif %}
  </ul>
</nav>


{% endblock %}

core/templates/core/salesperson.html
{% extends "core/base.html" %} {% block content %}



<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Address</th>
      <th scope="col">Phone number</th>
      <th scope="col">Start date</th>
      <th scope="col">Termination date</th>
      <th scope="col">Manager</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for item in data %}
    <tr>
      <td>{{ item.first_name }}</td>
      <td>{{ item.last_name }}</td>
      <td>{{ item.address }}</td>
      <td>{{ item.phone }}</td>
      <td>{{ item.start_date }}</td>
      <td>{{ item.termination_date }}</td>
      <td>{{ item.manager }}</td>
      <td>
        <a href="{% url 'core:salesperson_update' item.id %}" class="btn btn-outline-primary btn-sm" title="Edit">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square"
            viewBox="0 0 16 16">
            <path
              d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
            <path fill-rule="evenodd"
              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
          </svg>
        </a>
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table>

<nav>
  <ul class="pagination justify-content-center">
    {% if data.has_previous %}
    <li class="page-item">
      <a href="?page={{ data.previous_page_number }}" class="page-link">Previous</a>
    </li>
    {% endif %}

    {% for i in data.paginator.page_range %}
      {% if data.number == i %}
      <li class="page-item active"><a class="page-link" href="">{{ i }}</a></li>

      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if data.has_next %}
      <a class="page-link" href="?page={{ data.next_page_number }}">Next</a>
    {% endif %}
  </ul>
</nav>

{% endblock %}